openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for auth
paths:
    /login/{username}/{password}:
        get:
            tags:
                - auth
            summary: Login auth
            operationId: auth#Login
            parameters:
                - name: username
                  in: path
                  description: Raw username
                  required: true
                  schema:
                    type: string
                    description: Raw username
                    example: Fugit et voluptas soluta necessitatibus.
                  example: Illum ut repellendus velit qui.
                - name: password
                  in: path
                  description: User password
                  required: true
                  schema:
                    type: string
                    description: User password
                    example: Vero qui voluptatibus illum natus dignissimos.
                  example: Autem et et qui maiores.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Voluptatem impedit rem eligendi consectetur.
                            example: Sunt deserunt repudiandae quod consectetur quia.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Est sed accusamus temporibus.
                            example: Dolores et.
    /signup/{username}/{password}:
        get:
            tags:
                - auth
            summary: Signup auth
            operationId: auth#Signup
            parameters:
                - name: username
                  in: path
                  description: Raw username
                  required: true
                  schema:
                    type: string
                    description: Raw username
                    example: Illum ducimus et voluptatem.
                  example: Iure iure nam.
                - name: password
                  in: path
                  description: User password
                  required: true
                  schema:
                    type: string
                    description: User password
                    example: Distinctio ipsum ut nobis aperiam sit.
                  example: Voluptatem accusamus.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Eos recusandae quod porro.
                            example: Vel blanditiis ratione corrupti nostrum.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Autem rerum.
                            example: Debitis illo iusto maxime voluptas aliquid totam.
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 69
                        - 116
                        - 32
                        - 112
                        - 114
                        - 111
                        - 118
                        - 105
                        - 100
                        - 101
                        - 110
                        - 116
                        - 32
                        - 97
                        - 98
                        - 32
                        - 101
                        - 97
                        - 32
                        - 97
                        - 108
                        - 105
                        - 97
                        - 115
                        - 32
                        - 109
                        - 105
                        - 110
                        - 117
                        - 115
                        - 46
                    format: binary
                  example:
                    - 65
                    - 117
                    - 116
                    - 32
                    - 100
                    - 111
                    - 108
                    - 111
                    - 114
                    - 105
                    - 98
                    - 117
                    - 115
                    - 32
                    - 99
                    - 111
                    - 110
                    - 115
                    - 101
                    - 113
                    - 117
                    - 97
                    - 116
                    - 117
                    - 114
                    - 32
                    - 97
                    - 117
                    - 116
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Est dolor libero.
                            example: Illo voluptatem eligendi.
                    content:
                        application/json:
                            schema:
                                type: boolean
                                example: true
                            example: true
components: {}
tags:
    - name: auth
    - name: upload
