swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            parameters:
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
                - name: create_post_request_body
                  in: body
                  description: Post info
                  required: true
                  schema:
                    $ref: '#/definitions/PostingsCreatePostRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
                - name: SignupRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SignupSignupRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - signup_header_Authorization: []
definitions:
    PostingsCreatePostRequestBody:
        title: PostingsCreatePostRequestBody
        type: object
        properties:
            content:
                type: string
                description: Post content
                example:
                    - 65
                    - 117
                    - 116
                    - 32
                    - 113
                    - 117
                    - 105
                    - 32
                    - 99
                    - 117
                    - 109
                    - 32
                    - 116
                    - 101
                    - 109
                    - 112
                    - 111
                    - 114
                    - 105
                    - 98
                    - 117
                    - 115
                    - 32
                    - 97
                    - 115
                    - 112
                    - 101
                    - 114
                    - 105
                    - 111
                    - 114
                    - 101
                    - 115
                    - 32
                    - 113
                    - 117
                    - 105
                    - 46
                format: byte
            description:
                type: string
                description: Post description
                example: Dignissimos sed eius odio commodi eos consequatur.
            price:
                type: string
                description: Post price
                example: Quod aut alias optio quidem ducimus.
            title:
                type: string
                description: Post title
                example: Excepturi ut voluptatum.
        description: Describes a post
        example:
            content:
                - 77
                - 111
                - 100
                - 105
                - 32
                - 100
                - 111
                - 108
                - 111
                - 114
                - 101
                - 115
                - 32
                - 108
                - 97
                - 98
                - 111
                - 114
                - 117
                - 109
                - 46
            description: Voluptas quo.
            price: Quasi non qui esse non praesentium expedita.
            title: Eveniet incidunt et ut consequatur.
        required:
            - title
            - description
            - price
            - content
    SignupSignupRequestBody:
        title: SignupSignupRequestBody
        type: object
        properties:
            email:
                type: string
                description: Email
                example:
                    - 65
                    - 117
                    - 116
                    - 32
                    - 97
                    - 110
                    - 105
                    - 109
                    - 105
                    - 32
                    - 101
                    - 116
                    - 32
                    - 100
                    - 101
                    - 115
                    - 101
                    - 114
                    - 117
                    - 110
                    - 116
                    - 32
                    - 101
                    - 115
                    - 116
                    - 46
                format: byte
            firstName:
                type: string
                description: First name
                example: Quae autem quia nemo iste similique veritatis.
            lastName:
                type: string
                description: Last name
                example: At ad.
            phone:
                type: string
                description: Phone number
                example: Aut et atque.
        description: Describes a user
        example:
            email:
                - 68
                - 111
                - 108
                - 111
                - 114
                - 101
                - 109
                - 32
                - 101
                - 108
                - 105
                - 103
                - 101
                - 110
                - 100
                - 105
                - 32
                - 97
                - 117
                - 116
                - 32
                - 99
                - 111
                - 110
                - 115
                - 101
                - 113
                - 117
                - 97
                - 116
                - 117
                - 114
                - 32
                - 109
                - 105
                - 110
                - 105
                - 109
                - 97
                - 32
                - 114
                - 101
                - 109
                - 32
                - 116
                - 101
                - 109
                - 112
                - 111
                - 114
                - 97
                - 46
            firstName: Doloremque ut vel.
            lastName: Ab enim aut et quas quo.
            phone: Officiis est optio voluptates qui recusandae sit.
        required:
            - firstName
            - lastName
            - phone
            - email
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
        name: Authorization
        in: header
    login_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
    signup_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
