openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for auth
paths:
    /login:
        post:
            tags:
                - auth
            summary: Login auth
            operationId: auth#Login
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Soluta vero.
                            example: Perferendis autem et et qui maiores non.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Autem rerum.
                            example: Impedit rem eligendi consectetur voluptas rem error.
            security:
                - basic_header_Authorization: []
    /signup/{username}/{password}:
        get:
            tags:
                - auth
            summary: Signup auth
            operationId: auth#Signup
            parameters:
                - name: username
                  in: path
                  description: Raw username
                  required: true
                  schema:
                    type: string
                    description: Raw username
                    example: Sunt deserunt repudiandae quod consectetur quia.
                  example: Dolores et.
                - name: password
                  in: path
                  description: User password
                  required: true
                  schema:
                    type: string
                    description: User password
                    example: Illum ducimus et voluptatem.
                  example: Iure iure nam.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Distinctio ipsum ut nobis aperiam sit.
                            example: Eos recusandae quod porro.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Commodi fugit et voluptas.
                            example: Qui laudantium voluptatem assumenda ratione rem tempora.
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 86
                        - 101
                        - 108
                        - 32
                        - 98
                        - 108
                        - 97
                        - 110
                        - 100
                        - 105
                        - 116
                        - 105
                        - 105
                        - 115
                        - 32
                        - 114
                        - 97
                        - 116
                        - 105
                        - 111
                        - 110
                        - 101
                        - 32
                        - 99
                        - 111
                        - 114
                        - 114
                        - 117
                        - 112
                        - 116
                        - 105
                        - 32
                        - 110
                        - 111
                        - 115
                        - 116
                        - 114
                        - 117
                        - 109
                        - 46
                    format: binary
                  example:
                    - 68
                    - 101
                    - 98
                    - 105
                    - 116
                    - 105
                    - 115
                    - 32
                    - 105
                    - 108
                    - 108
                    - 111
                    - 32
                    - 105
                    - 117
                    - 115
                    - 116
                    - 111
                    - 32
                    - 109
                    - 97
                    - 120
                    - 105
                    - 109
                    - 101
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 115
                    - 32
                    - 97
                    - 108
                    - 105
                    - 113
                    - 117
                    - 105
                    - 100
                    - 32
                    - 116
                    - 111
                    - 116
                    - 97
                    - 109
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Et provident ab ea alias minus.
                            example: Est dolor libero.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Necessitatibus ipsam illum ut repellendus velit.
                            example: Minus cupiditate adipisci omnis ex porro.
            security:
                - jwt_header_Authorization: []
components:
    securitySchemes:
        basic_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
tags:
    - name: auth
    - name: upload
