openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Autem neque numquam.
                            example: Velit rerum occaecati quia.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Nisi tempora delectus architecto.
                            example: Voluptate quod.
            security:
                - signup_header_Authorization: []
    /upload/{content}:
        post:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 68
                        - 111
                        - 108
                        - 111
                        - 114
                        - 117
                        - 109
                        - 32
                        - 97
                        - 117
                        - 116
                        - 32
                        - 97
                        - 117
                        - 116
                        - 32
                        - 105
                        - 109
                        - 112
                        - 101
                        - 100
                        - 105
                        - 116
                        - 32
                        - 110
                        - 105
                        - 115
                        - 105
                        - 32
                        - 111
                        - 100
                        - 105
                        - 111
                        - 46
                    format: binary
                  example:
                    - 67
                    - 111
                    - 109
                    - 109
                    - 111
                    - 100
                    - 105
                    - 32
                    - 111
                    - 102
                    - 102
                    - 105
                    - 99
                    - 105
                    - 105
                    - 115
                    - 32
                    - 110
                    - 117
                    - 109
                    - 113
                    - 117
                    - 97
                    - 109
                    - 32
                    - 109
                    - 111
                    - 108
                    - 101
                    - 115
                    - 116
                    - 105
                    - 97
                    - 101
                    - 46
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Odit nesciunt dicta tempore fugiat.
                            example: Nam doloribus dolor commodi consequuntur perferendis ea.
            security:
                - jwt_header_Authorization: []
components:
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: upload
