openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Aut id placeat voluptate expedita sunt culpa.
                            example: Minima nisi.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                description: Email
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: Email
                            example: Voluptatibus cupiditate ea cum ut beatae.
                        example: Ut ut omnis.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Magnam non voluptas aut vero pariatur.
                            example: Ut molestiae nihil ipsam voluptatem explicabo qui.
            security:
                - signup_header_Authorization: []
    /upload:
        post:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            requestBody:
                description: photo content
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: photo content
                            example:
                                - 85
                                - 116
                                - 32
                                - 105
                                - 110
                                - 32
                                - 115
                                - 97
                                - 112
                                - 105
                                - 101
                                - 110
                                - 116
                                - 101
                                - 32
                                - 105
                                - 108
                                - 108
                                - 111
                                - 32
                                - 101
                                - 120
                                - 112
                                - 108
                                - 105
                                - 99
                                - 97
                                - 98
                                - 111
                                - 32
                                - 97
                                - 117
                                - 116
                                - 46
                            format: binary
                        example:
                            - 81
                            - 117
                            - 97
                            - 101
                            - 32
                            - 97
                            - 117
                            - 116
                            - 101
                            - 109
                            - 32
                            - 113
                            - 117
                            - 105
                            - 97
                            - 32
                            - 110
                            - 101
                            - 109
                            - 111
                            - 32
                            - 105
                            - 115
                            - 116
                            - 101
                            - 32
                            - 115
                            - 105
                            - 109
                            - 105
                            - 108
                            - 105
                            - 113
                            - 117
                            - 101
                            - 32
                            - 118
                            - 101
                            - 114
                            - 105
                            - 116
                            - 97
                            - 116
                            - 105
                            - 115
                            - 46
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Autem quia veritatis dolorem.
                            example: At ad.
            security:
                - jwt_header_Authorization: []
components:
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: upload
