swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            parameters:
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
                - name: create_post_request_body
                  in: body
                  description: Post info
                  required: true
                  schema:
                    $ref: '#/definitions/PostingsCreatePostRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PostingsCreatePostResponseBody'
                        required:
                            - title
                            - description
                            - price
                            - imageID
                            - postID
                            - uploadDate
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - login_header_Authorization: []
    /posts/{page}:
        get:
            tags:
                - postings
            summary: get_post_page postings
            operationId: postings#get_post_page
            parameters:
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/PostResponse'
            schemes:
                - http
    /posts/{postID}:
        get:
            tags:
                - postings
            summary: get_images_for_post postings
            operationId: postings#get_images_for_post
            parameters:
                - name: postID
                  in: path
                  description: Post to get images for
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Voluptates ut.
            schemes:
                - http
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
                - name: SignupRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SignupSignupRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - signup_header_Authorization: []
definitions:
    PostResponse:
        title: PostResponse
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Explicabo repellendus modi et.
            imageID:
                type: string
                description: Image ID
                example: Vitae laudantium quo laboriosam totam ad quia.
            postID:
                type: string
                description: Post ID
                example: Nesciunt enim optio quia debitis totam temporibus.
            price:
                type: string
                description: Post price
                example: Voluptas et impedit qui praesentium autem.
            title:
                type: string
                description: Post title
                example: Dolores nostrum suscipit rerum consequatur.
            uploadDate:
                type: string
                description: Upload Date
                example: Cumque dolores aut excepturi atque ut quidem.
        description: Describes a post
        example:
            description: Omnis odio molestiae nesciunt natus vitae.
            imageID: Ab a consequatur enim quasi qui.
            postID: Doloremque ut non.
            price: Et voluptatem quia quidem recusandae qui.
            title: Dolores blanditiis ut culpa.
            uploadDate: Enim quo.
        required:
            - title
            - description
            - price
            - imageID
            - postID
            - uploadDate
    PostResponseResponseBody:
        title: PostResponseResponseBody
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Tempora vero.
            imageID:
                type: string
                description: Image ID
                example: Est inventore.
            postID:
                type: string
                description: Post ID
                example: Cupiditate voluptatem a eaque odit.
            price:
                type: string
                description: Post price
                example: Provident ipsa dignissimos sed.
            title:
                type: string
                description: Post title
                example: Sit et quaerat non nobis repudiandae autem.
            uploadDate:
                type: string
                description: Upload Date
                example: Atque voluptates at perferendis.
        description: Describes a post
        example:
            description: Distinctio ut laboriosam nam hic vel vel.
            imageID: Architecto et expedita eum voluptatibus tenetur non.
            postID: Odit deleniti non praesentium molestiae consequuntur.
            price: Dignissimos repellendus quia.
            title: Provident dignissimos.
            uploadDate: Eum molestiae ut deleniti laborum.
        required:
            - title
            - description
            - price
            - imageID
            - postID
            - uploadDate
    PostingsCreatePostRequestBody:
        title: PostingsCreatePostRequestBody
        type: object
        properties:
            content:
                type: string
                description: Post content
                example:
                    - 70
                    - 97
                    - 99
                    - 101
                    - 114
                    - 101
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 117
                    - 109
                    - 32
                    - 113
                    - 117
                    - 105
                    - 115
                    - 32
                    - 100
                    - 111
                    - 108
                    - 111
                    - 114
                    - 101
                    - 115
                    - 32
                    - 113
                    - 117
                    - 105
                    - 46
                format: byte
            description:
                type: string
                description: Post description
                example: Voluptas commodi.
            price:
                type: string
                description: Post price
                example: Est et aut doloribus nobis dolorem.
            title:
                type: string
                description: Post title
                example: Minus quia labore recusandae quae omnis et.
        description: Describes a post
        example:
            content:
                - 69
                - 97
                - 32
                - 109
                - 97
                - 103
                - 110
                - 105
                - 32
                - 102
                - 117
                - 103
                - 105
                - 116
                - 32
                - 97
                - 112
                - 101
                - 114
                - 105
                - 97
                - 109
                - 32
                - 101
                - 117
                - 109
                - 46
            description: Ut blanditiis deleniti illo.
            price: Libero a id aut.
            title: Ullam perferendis.
        required:
            - title
            - description
            - price
            - content
    PostingsCreatePostResponseBody:
        title: PostingsCreatePostResponseBody
        $ref: '#/definitions/PostResponseResponseBody'
    SignupSignupRequestBody:
        title: SignupSignupRequestBody
        type: object
        properties:
            email:
                type: string
                description: Email
                example: Ipsum rerum iure minima nihil odio.
            firstName:
                type: string
                description: First name
                example: Ipsum facilis qui.
            lastName:
                type: string
                description: Last name
                example: Praesentium distinctio impedit.
            phone:
                type: string
                description: Phone number
                example: Aut totam.
        description: Describes a user
        example:
            email: Excepturi quos ut.
            firstName: Dolorem aut hic dolores est.
            lastName: Eaque nesciunt impedit aut rerum qui.
            phone: Minima quis numquam.
        required:
            - firstName
            - lastName
            - phone
            - email
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
        name: Authorization
        in: header
    login_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
    signup_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
