openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            requestBody:
                description: Post info
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Post'
                        example:
                            content:
                                - 69
                                - 97
                                - 114
                                - 117
                                - 109
                                - 32
                                - 113
                                - 117
                                - 105
                                - 97
                                - 32
                                - 97
                                - 117
                                - 116
                                - 46
                            description: Nam doloribus dolor commodi consequuntur perferendis ea.
                            price: Qui unde et mollitia modi.
                            title: Commodi officiis numquam molestiae.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Atque voluptates at perferendis.
                            example: Dignissimos repellendus quia.
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Aut qui cum temporibus asperiores qui.
                            example: Provident dignissimos.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
                        example:
                            email:
                                - 78
                                - 105
                                - 115
                                - 105
                                - 32
                                - 116
                                - 101
                                - 109
                                - 112
                                - 111
                                - 114
                                - 97
                                - 32
                                - 100
                                - 101
                                - 108
                                - 101
                                - 99
                                - 116
                                - 117
                                - 115
                                - 32
                                - 97
                                - 114
                                - 99
                                - 104
                                - 105
                                - 116
                                - 101
                                - 99
                                - 116
                                - 111
                                - 46
                            firstName: Laborum ut iste et harum.
                            lastName: Unde quod.
                            phone: Autem neque numquam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Dolorem aut hic dolores est.
                            example: Distinctio ut laboriosam nam hic vel vel.
            security:
                - signup_header_Authorization: []
components:
    schemas:
        Post:
            type: object
            properties:
                content:
                    type: string
                    description: Post content
                    example:
                        - 83
                        - 105
                        - 116
                        - 32
                        - 101
                        - 116
                        - 32
                        - 113
                        - 117
                        - 97
                        - 101
                        - 114
                        - 97
                        - 116
                        - 32
                        - 110
                        - 111
                        - 110
                        - 32
                        - 110
                        - 111
                        - 98
                        - 105
                        - 115
                        - 32
                        - 114
                        - 101
                        - 112
                        - 117
                        - 100
                        - 105
                        - 97
                        - 110
                        - 100
                        - 97
                        - 101
                        - 32
                        - 97
                        - 117
                        - 116
                        - 101
                        - 109
                        - 46
                    format: binary
                description:
                    type: string
                    description: Post description
                    example: Minima quis numquam.
                price:
                    type: string
                    description: Post price
                    example: Excepturi quos ut.
                title:
                    type: string
                    description: Post title
                    example: Eaque nesciunt impedit aut rerum qui.
            description: Describes a post
            example:
                content:
                    - 67
                    - 117
                    - 112
                    - 105
                    - 100
                    - 105
                    - 116
                    - 97
                    - 116
                    - 101
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 101
                    - 109
                    - 32
                    - 97
                    - 32
                    - 101
                    - 97
                    - 113
                    - 117
                    - 101
                    - 32
                    - 111
                    - 100
                    - 105
                    - 116
                    - 46
                description: Provident ipsa dignissimos sed.
                price: Est inventore.
                title: Tempora vero.
            required:
                - title
                - description
                - price
                - content
        User:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example:
                        - 77
                        - 111
                        - 100
                        - 105
                        - 32
                        - 100
                        - 111
                        - 108
                        - 111
                        - 114
                        - 101
                        - 115
                        - 32
                        - 108
                        - 97
                        - 98
                        - 111
                        - 114
                        - 117
                        - 109
                        - 46
                    format: binary
                firstName:
                    type: string
                    description: First name
                    example: Eveniet incidunt et ut consequatur.
                lastName:
                    type: string
                    description: Last name
                    example: Voluptas quo.
                phone:
                    type: string
                    description: Phone number
                    example: Quasi non qui esse non praesentium expedita.
            description: Describes a user
            example:
                email:
                    - 86
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 115
                    - 32
                    - 105
                    - 112
                    - 115
                    - 117
                    - 109
                    - 32
                    - 114
                    - 101
                    - 114
                    - 117
                    - 109
                    - 32
                    - 105
                    - 117
                    - 114
                    - 101
                    - 32
                    - 109
                    - 105
                    - 110
                    - 105
                    - 109
                    - 97
                    - 32
                    - 110
                    - 105
                    - 104
                    - 105
                    - 108
                    - 32
                    - 111
                    - 100
                    - 105
                    - 111
                    - 46
                firstName: Repudiandae tempore molestiae illo.
                lastName: Incidunt et ipsum facilis.
                phone: Neque praesentium distinctio impedit perferendis aut.
            required:
                - firstName
                - lastName
                - phone
                - email
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: postings
