openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Aut id placeat voluptate expedita sunt culpa.
                            example: Ut in sapiente illo explicabo aut.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            parameters:
                - name: firstName
                  in: query
                  description: User first name
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User first name
                    example: Autem quia veritatis dolorem.
                  example: Minima nisi.
                - name: lastName
                  in: query
                  description: User last name
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User last name
                    example: Ut ut omnis.
                  example: Ut molestiae nihil ipsam voluptatem explicabo qui.
                - name: email
                  in: query
                  description: User email
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User email
                    example: Quae autem quia nemo iste similique veritatis.
                  example: At ad.
                - name: phone
                  in: query
                  description: User phone number
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: User phone number
                    example: Aut et atque.
                  example: Aut animi et deserunt est.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Voluptatibus cupiditate ea cum ut beatae.
                            example: Doloremque ut vel.
            security:
                - signup_header_Authorization: []
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 65
                        - 98
                        - 32
                        - 101
                        - 110
                        - 105
                        - 109
                        - 32
                        - 97
                        - 117
                        - 116
                        - 32
                        - 101
                        - 116
                        - 32
                        - 113
                        - 117
                        - 97
                        - 115
                        - 32
                        - 113
                        - 117
                        - 111
                        - 46
                    format: binary
                  example:
                    - 79
                    - 102
                    - 102
                    - 105
                    - 99
                    - 105
                    - 105
                    - 115
                    - 32
                    - 101
                    - 115
                    - 116
                    - 32
                    - 111
                    - 112
                    - 116
                    - 105
                    - 111
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 101
                    - 115
                    - 32
                    - 113
                    - 117
                    - 105
                    - 32
                    - 114
                    - 101
                    - 99
                    - 117
                    - 115
                    - 97
                    - 110
                    - 100
                    - 97
                    - 101
                    - 32
                    - 115
                    - 105
                    - 116
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Dolorem eligendi aut consequatur minima rem tempora.
                            example: Dignissimos sed eius odio commodi eos consequatur.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Magnam non voluptas aut vero pariatur.
                            example: Quod aut alias optio quidem ducimus.
            security:
                - jwt_header_Authorization: []
components:
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: upload
