openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Credentials:
                            schema:
                                type: string
                                example: Aut animi et deserunt est.
                            example: Ab enim aut et quas quo.
                        Access-Control-Allow-Methods:
                            schema:
                                type: string
                                example: Minima nisi.
                            example: Ut molestiae nihil ipsam voluptatem explicabo qui.
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Quae autem quia nemo iste similique veritatis.
                            example: Aut et atque.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Magnam non voluptas aut vero pariatur.
                            example: Officiis est optio voluptates qui recusandae sit.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Credentials:
                            schema:
                                type: string
                                example: Quod aut alias optio quidem ducimus.
                            example: Eveniet incidunt et ut consequatur.
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Dolorem eligendi aut consequatur minima rem tempora.
                            example: Dignissimos sed eius odio commodi eos consequatur.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Ut in sapiente illo explicabo aut.
                            example: Voluptas quo.
            security:
                - signup_header_Authorization: []
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 81
                        - 117
                        - 97
                        - 115
                        - 105
                        - 32
                        - 110
                        - 111
                        - 110
                        - 32
                        - 113
                        - 117
                        - 105
                        - 32
                        - 101
                        - 115
                        - 115
                        - 101
                        - 32
                        - 110
                        - 111
                        - 110
                        - 32
                        - 112
                        - 114
                        - 97
                        - 101
                        - 115
                        - 101
                        - 110
                        - 116
                        - 105
                        - 117
                        - 109
                        - 32
                        - 101
                        - 120
                        - 112
                        - 101
                        - 100
                        - 105
                        - 116
                        - 97
                        - 46
                    format: binary
                  example:
                    - 77
                    - 111
                    - 100
                    - 105
                    - 32
                    - 100
                    - 111
                    - 108
                    - 111
                    - 114
                    - 101
                    - 115
                    - 32
                    - 108
                    - 97
                    - 98
                    - 111
                    - 114
                    - 117
                    - 109
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Repudiandae tempore molestiae illo.
                            example: Neque praesentium distinctio impedit perferendis aut.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Autem quia veritatis dolorem.
                            example: Voluptas ipsum rerum iure minima nihil odio.
            security:
                - jwt_header_Authorization: []
components:
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: upload
