swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            parameters:
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
                - name: create_post_request_body
                  in: body
                  description: Post info
                  required: true
                  schema:
                    $ref: '#/definitions/PostingsCreatePostRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PostingsCreatePostResponseBody'
                        required:
                            - title
                            - description
                            - price
                            - imageIDs
                            - postID
                            - medium
                            - uploadDate
                            - sold
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - login_header_Authorization: []
    /posts/delete/{postID}:
        delete:
            tags:
                - postings
            summary: delete_post postings
            operationId: postings#delete_post
            parameters:
                - name: postID
                  in: path
                  description: Post to delete
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /posts/edit/{postID}:
        put:
            tags:
                - postings
            summary: edit_post postings
            operationId: postings#edit_post
            parameters:
                - name: title
                  in: query
                  description: Post title
                  required: false
                  type: string
                - name: description
                  in: query
                  description: Post description
                  required: false
                  type: string
                - name: price
                  in: query
                  description: Post price
                  required: false
                  type: string
                - name: content
                  in: query
                  description: Image content
                  required: false
                  type: string
                - name: medium
                  in: query
                  description: Art type
                  required: false
                  type: string
                - name: sold
                  in: query
                  description: is sold
                  required: false
                  type: boolean
                - name: imageID
                  in: query
                  description: Image ID
                  required: false
                  type: string
                - name: postID
                  in: path
                  description: Post ID
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PostingsEditPostResponseBody'
                        required:
                            - title
                            - description
                            - price
                            - imageIDs
                            - postID
                            - medium
                            - uploadDate
                            - sold
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /posts/getimages/{postID}:
        get:
            tags:
                - postings
            summary: get_images_for_post postings
            operationId: postings#get_images_for_post
            parameters:
                - name: postID
                  in: path
                  description: Post to get images for
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Sed adipisci ducimus ut.
            schemes:
                - http
    /posts/getpage/{page}:
        get:
            tags:
                - postings
            summary: get_post_page postings
            operationId: postings#get_post_page
            parameters:
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/PostResponse'
            schemes:
                - http
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
                - name: SignupRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SignupSignupRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - signup_header_Authorization: []
definitions:
    PostResponse:
        title: PostResponse
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Nisi similique sunt.
            imageIDs:
                type: array
                items:
                    type: string
                    example: Iste qui sit ut.
                description: Image ID
                example:
                    - Distinctio error est sint eos.
                    - Assumenda non.
                    - Eaque aut cupiditate ut aut dolor.
            medium:
                type: string
                description: Art type
                example: Aut est non ad eum modi.
            postID:
                type: string
                description: Post ID
                example: Qui omnis maiores quod accusamus.
            price:
                type: string
                description: Post price
                example: Quibusdam sed repellendus aliquam voluptatem.
            sold:
                type: boolean
                description: is sold
                example: false
            title:
                type: string
                description: Post title
                example: Dicta dolorem iure dolor.
            uploadDate:
                type: string
                description: Upload Date
                example: Et sit quia omnis nemo.
        description: Describes a post
        example:
            description: Qui velit voluptatibus nam minus in ratione.
            imageIDs:
                - Earum perspiciatis odit.
                - Ex rem rerum numquam veniam.
            medium: Doloremque dolorem autem provident.
            postID: Repudiandae quo rerum porro eius officia.
            price: Dignissimos et distinctio.
            sold: true
            title: Tempora velit asperiores qui qui optio tenetur.
            uploadDate: Accusamus delectus hic.
        required:
            - title
            - description
            - price
            - imageIDs
            - postID
            - medium
            - uploadDate
            - sold
    PostResponseResponseBody:
        title: PostResponseResponseBody
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Cumque mollitia et minus.
            imageIDs:
                type: array
                items:
                    type: string
                    example: Cum dolor totam sint saepe aperiam non.
                description: Image ID
                example:
                    - Ex qui.
                    - Consectetur ratione.
                    - Nemo numquam iste.
                    - Ad voluptatem id dolor autem iusto.
            medium:
                type: string
                description: Art type
                example: Porro qui vel sed et tenetur.
            postID:
                type: string
                description: Post ID
                example: Qui unde natus.
            price:
                type: string
                description: Post price
                example: Veritatis delectus eaque.
            sold:
                type: boolean
                description: is sold
                example: true
            title:
                type: string
                description: Post title
                example: Odit quia culpa vero sed.
            uploadDate:
                type: string
                description: Upload Date
                example: Delectus animi.
        description: Describes a post
        example:
            description: Corporis minima qui sit sed voluptas.
            imageIDs:
                - Doloremque eos repellendus.
                - Aut ullam eius.
                - Beatae iure consequatur.
            medium: Et vel ipsam suscipit earum.
            postID: Incidunt neque et.
            price: Et magnam ea omnis quo enim voluptatem.
            sold: false
            title: Quaerat ipsa enim.
            uploadDate: Repudiandae consequatur voluptatibus.
        required:
            - title
            - description
            - price
            - imageIDs
            - postID
            - medium
            - uploadDate
            - sold
    PostingsCreatePostRequestBody:
        title: PostingsCreatePostRequestBody
        type: object
        properties:
            content:
                type: array
                items:
                    type: string
                    example: Officiis qui provident nam voluptatem.
                description: Post content
                example:
                    - Velit pariatur culpa odio adipisci.
                    - Qui animi recusandae magni.
                    - Sunt corrupti sequi nesciunt quam dolorem minima.
            description:
                type: string
                description: Post description
                example: Est occaecati harum cum officia quas deleniti.
            medium:
                type: string
                description: Art type
                example: Maxime rerum.
            price:
                type: string
                description: Post price
                example: Voluptates vel.
            title:
                type: string
                description: Post title
                example: Omnis eum enim.
        description: Describes a post
        example:
            content:
                - Non quidem eos.
                - Veniam voluptatem aperiam eum non occaecati architecto.
            description: Sapiente labore quia.
            medium: Facere ratione neque.
            price: Non illum eum nihil inventore voluptatibus maxime.
            title: Vel adipisci.
        required:
            - title
            - description
            - price
            - content
            - medium
    PostingsCreatePostResponseBody:
        title: PostingsCreatePostResponseBody
        $ref: '#/definitions/PostResponseResponseBody'
    PostingsEditPostResponseBody:
        title: PostingsEditPostResponseBody
        $ref: '#/definitions/PostResponseResponseBody'
    SignupSignupRequestBody:
        title: SignupSignupRequestBody
        type: object
        properties:
            email:
                type: string
                description: Email
                example: Vel culpa ut expedita consequatur facilis non.
            firstName:
                type: string
                description: First name
                example: Enim quo.
            lastName:
                type: string
                description: Last name
                example: Voluptates ut.
            phone:
                type: string
                description: Phone number
                example: Id ut et.
        description: Describes a user
        example:
            email: Aut sunt ut.
            firstName: Dolores praesentium vel blanditiis nihil blanditiis porro.
            lastName: In vero voluptatem saepe tempore eius ducimus.
            phone: Sit distinctio est corrupti suscipit aperiam aut.
        required:
            - firstName
            - lastName
            - phone
            - email
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
        name: Authorization
        in: header
    login_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
    signup_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
