openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Credentials:
                            schema:
                                type: string
                                example: Ut ut omnis.
                            example: Quae autem quia nemo iste similique veritatis.
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Ut in sapiente illo explicabo aut.
                            example: Minima nisi.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Aut id placeat voluptate expedita sunt culpa.
                            example: At ad.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Credentials:
                            schema:
                                type: string
                                example: Ab enim aut et quas quo.
                            example: Dolorem eligendi aut consequatur minima rem tempora.
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Aut et atque.
                            example: Doloremque ut vel.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Voluptatibus cupiditate ea cum ut beatae.
                            example: Excepturi ut voluptatum.
            security:
                - signup_header_Authorization: []
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 68
                        - 105
                        - 103
                        - 110
                        - 105
                        - 115
                        - 115
                        - 105
                        - 109
                        - 111
                        - 115
                        - 32
                        - 115
                        - 101
                        - 100
                        - 32
                        - 101
                        - 105
                        - 117
                        - 115
                        - 32
                        - 111
                        - 100
                        - 105
                        - 111
                        - 32
                        - 99
                        - 111
                        - 109
                        - 109
                        - 111
                        - 100
                        - 105
                        - 32
                        - 101
                        - 111
                        - 115
                        - 32
                        - 99
                        - 111
                        - 110
                        - 115
                        - 101
                        - 113
                        - 117
                        - 97
                        - 116
                        - 117
                        - 114
                        - 46
                    format: binary
                  example:
                    - 81
                    - 117
                    - 111
                    - 100
                    - 32
                    - 97
                    - 117
                    - 116
                    - 32
                    - 97
                    - 108
                    - 105
                    - 97
                    - 115
                    - 32
                    - 111
                    - 112
                    - 116
                    - 105
                    - 111
                    - 32
                    - 113
                    - 117
                    - 105
                    - 100
                    - 101
                    - 109
                    - 32
                    - 100
                    - 117
                    - 99
                    - 105
                    - 109
                    - 117
                    - 115
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Aut qui cum temporibus asperiores qui.
                            example: Voluptas quo.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Magnam non voluptas aut vero pariatur.
                            example: Quasi non qui esse non praesentium expedita.
            security:
                - jwt_header_Authorization: []
components:
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: upload
