openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quae autem quia nemo iste similique veritatis.
                            example: Eveniet incidunt et ut consequatur.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
                        example:
                            email: Laborum ut iste et harum.
                            firstName: Reiciendis voluptas in autem dolorem.
                            lastName: Corporis ipsum neque.
                            phone: Unde vero.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Dignissimos sed eius odio commodi eos consequatur.
                            example: Voluptas quo.
            security:
                - signup_header_Authorization: []
    /upload:
        post:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            requestBody:
                description: photo content
                required: true
                content:
                    application/json:
                        schema:
                            type: string
                            description: photo content
                            example:
                                - 81
                                - 117
                                - 111
                                - 100
                                - 32
                                - 97
                                - 117
                                - 116
                                - 32
                                - 97
                                - 108
                                - 105
                                - 97
                                - 115
                                - 32
                                - 111
                                - 112
                                - 116
                                - 105
                                - 111
                                - 32
                                - 113
                                - 117
                                - 105
                                - 100
                                - 101
                                - 109
                                - 32
                                - 100
                                - 117
                                - 99
                                - 105
                                - 109
                                - 117
                                - 115
                                - 46
                            format: binary
                        example:
                            - 81
                            - 117
                            - 97
                            - 115
                            - 105
                            - 32
                            - 110
                            - 111
                            - 110
                            - 32
                            - 113
                            - 117
                            - 105
                            - 32
                            - 101
                            - 115
                            - 115
                            - 101
                            - 32
                            - 110
                            - 111
                            - 110
                            - 32
                            - 112
                            - 114
                            - 97
                            - 101
                            - 115
                            - 101
                            - 110
                            - 116
                            - 105
                            - 117
                            - 109
                            - 32
                            - 101
                            - 120
                            - 112
                            - 101
                            - 100
                            - 105
                            - 116
                            - 97
                            - 46
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Aut qui cum temporibus asperiores qui.
                            example: Modi dolores laborum.
            security:
                - jwt_header_Authorization: []
components:
    schemas:
        User:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Doloremque ut vel.
                firstName:
                    type: string
                    description: First name
                    example: At ad.
                lastName:
                    type: string
                    description: Last name
                    example: Aut et atque.
                phone:
                    type: string
                    description: Phone number
                    example: Aut animi et deserunt est.
            description: Describes a user
            example:
                email: Excepturi ut voluptatum.
                firstName: Ab enim aut et quas quo.
                lastName: Officiis est optio voluptates qui recusandae sit.
                phone: Dolorem eligendi aut consequatur minima rem tempora.
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: upload
