openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            requestBody:
                description: Post info
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Post'
                        example:
                            content:
                                - 85
                                - 116
                                - 32
                                - 117
                                - 116
                                - 32
                                - 111
                                - 109
                                - 110
                                - 105
                                - 115
                                - 46
                            description: Autem quia veritatis dolorem.
                            price: Minima nisi.
                            title: Ut in sapiente illo explicabo aut.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostingscreatePostResponseBody'
                            example:
                                description: At ad.
                                imageID: Aut animi et deserunt est.
                                postID: Doloremque ut vel.
                                price: Aut et atque.
                                title: Quae autem quia nemo iste similique veritatis.
                                uploadDate: Ab enim aut et quas quo.
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Vitae laudantium quo laboriosam totam ad quia.
                            example: Laudantium aut ullam eius ipsa.
            security:
                - login_header_Authorization: []
    /posts/{page}:
        get:
            tags:
                - postings
            summary: get_post_page postings
            operationId: postings#get_post_page
            parameters:
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  schema:
                    type: integer
                    description: Page to get posts for
                    example: 5206077168598330888
                    format: int64
                  example: 3762369825311389636
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/PostResponse'
                                example:
                                    - description: Et incidunt assumenda sequi.
                                      imageID: Corporis ipsum neque.
                                      postID: Unde vero.
                                      price: Reiciendis voluptas in autem dolorem.
                                      title: Accusantium ipsam nisi pariatur magnam.
                                      uploadDate: Laborum ut iste et harum.
                                    - description: Et incidunt assumenda sequi.
                                      imageID: Corporis ipsum neque.
                                      postID: Unde vero.
                                      price: Reiciendis voluptas in autem dolorem.
                                      title: Accusantium ipsam nisi pariatur magnam.
                                      uploadDate: Laborum ut iste et harum.
                                    - description: Et incidunt assumenda sequi.
                                      imageID: Corporis ipsum neque.
                                      postID: Unde vero.
                                      price: Reiciendis voluptas in autem dolorem.
                                      title: Accusantium ipsam nisi pariatur magnam.
                                      uploadDate: Laborum ut iste et harum.
                                    - description: Et incidunt assumenda sequi.
                                      imageID: Corporis ipsum neque.
                                      postID: Unde vero.
                                      price: Reiciendis voluptas in autem dolorem.
                                      title: Accusantium ipsam nisi pariatur magnam.
                                      uploadDate: Laborum ut iste et harum.
                            example:
                                - description: Et incidunt assumenda sequi.
                                  imageID: Corporis ipsum neque.
                                  postID: Unde vero.
                                  price: Reiciendis voluptas in autem dolorem.
                                  title: Accusantium ipsam nisi pariatur magnam.
                                  uploadDate: Laborum ut iste et harum.
                                - description: Et incidunt assumenda sequi.
                                  imageID: Corporis ipsum neque.
                                  postID: Unde vero.
                                  price: Reiciendis voluptas in autem dolorem.
                                  title: Accusantium ipsam nisi pariatur magnam.
                                  uploadDate: Laborum ut iste et harum.
            security:
                - jwt_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
                        example:
                            email: Qui unde et mollitia modi.
                            firstName: Dolorum aut aut impedit nisi odio.
                            lastName: Commodi officiis numquam molestiae.
                            phone: Nam doloribus dolor commodi consequuntur perferendis ea.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Voluptates ut.
                            example: Iure consequatur eos.
            security:
                - signup_header_Authorization: []
components:
    schemas:
        Post:
            type: object
            properties:
                content:
                    type: string
                    description: Post content
                    example:
                        - 73
                        - 110
                        - 32
                        - 118
                        - 101
                        - 114
                        - 111
                        - 32
                        - 118
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 116
                        - 101
                        - 109
                        - 32
                        - 115
                        - 97
                        - 101
                        - 112
                        - 101
                        - 32
                        - 116
                        - 101
                        - 109
                        - 112
                        - 111
                        - 114
                        - 101
                        - 32
                        - 101
                        - 105
                        - 117
                        - 115
                        - 32
                        - 100
                        - 117
                        - 99
                        - 105
                        - 109
                        - 117
                        - 115
                        - 46
                    format: binary
                description:
                    type: string
                    description: Post description
                    example: Vel culpa ut expedita consequatur facilis non.
                price:
                    type: string
                    description: Post price
                    example: Dolores praesentium vel blanditiis nihil blanditiis porro.
                title:
                    type: string
                    description: Post title
                    example: Id ut et.
            description: Describes a post
            example:
                content:
                    - 67
                    - 117
                    - 109
                    - 113
                    - 117
                    - 101
                    - 32
                    - 109
                    - 111
                    - 108
                    - 108
                    - 105
                    - 116
                    - 105
                    - 97
                    - 32
                    - 101
                    - 116
                    - 32
                    - 109
                    - 105
                    - 110
                    - 117
                    - 115
                    - 46
                description: Aut sunt ut.
                price: Odit quia culpa vero sed.
                title: Sit distinctio est corrupti suscipit aperiam aut.
            required:
                - title
                - description
                - price
                - content
        PostResponse:
            type: object
            properties:
                description:
                    type: string
                    description: Post description
                    example: Cum dolor totam sint saepe aperiam non.
                imageID:
                    type: string
                    description: Image ID
                    example: Nemo numquam iste.
                postID:
                    type: string
                    description: Post ID
                    example: Ad voluptatem id dolor autem iusto.
                price:
                    type: string
                    description: Post price
                    example: Id ex qui occaecati consectetur ratione.
                title:
                    type: string
                    description: Post title
                    example: Veritatis delectus eaque.
                uploadDate:
                    type: string
                    description: Upload Date
                    example: Qui unde natus.
            description: Describes a post
            example:
                description: Delectus animi.
                imageID: Qui sit.
                postID: Voluptas minus et magnam.
                price: Non quaerat ipsa enim eos corporis.
                title: Porro qui vel sed et tenetur.
                uploadDate: Omnis quo enim voluptatem eligendi libero doloremque.
            required:
                - title
                - description
                - price
                - imageID
                - postID
                - uploadDate
        PostingscreatePostResponseBody:
            $ref: '#/components/schemas/PostResponse'
        User:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Omnis odio molestiae nesciunt natus vitae.
                firstName:
                    type: string
                    description: First name
                    example: Nesciunt enim optio quia debitis totam temporibus.
                lastName:
                    type: string
                    description: Last name
                    example: Cumque dolores aut excepturi atque ut quidem.
                phone:
                    type: string
                    description: Phone number
                    example: Dolores blanditiis ut culpa.
            description: Describes a user
            example:
                email: Enim quo.
                firstName: Et voluptatem quia quidem recusandae qui.
                lastName: Ab a consequatur enim quasi qui.
                phone: Doloremque ut non.
            required:
                - firstName
                - lastName
                - phone
                - email
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: postings
