openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for auth
paths:
    /login/{username}/{password}:
        get:
            tags:
                - auth
            summary: Login auth
            operationId: auth#Login
            parameters:
                - name: username
                  in: path
                  description: Raw username
                  required: true
                  schema:
                    type: string
                    description: Raw username
                    example: Voluptas soluta.
                  example: Ipsam illum ut repellendus velit qui soluta.
                - name: password
                  in: path
                  description: User password
                  required: true
                  schema:
                    type: string
                    description: User password
                    example: Qui voluptatibus.
                  example: Natus dignissimos perferendis autem et et qui.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Non voluptatem impedit rem.
                            example: Repudiandae quod consectetur quia rerum.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quia laborum quam voluptatem quia sapiente est.
                            example: Et minus illum ducimus et.
    /signup/{username}/{password}:
        get:
            tags:
                - auth
            summary: Signup auth
            operationId: auth#Signup
            parameters:
                - name: username
                  in: path
                  description: Raw username
                  required: true
                  schema:
                    type: string
                    description: Raw username
                    example: Unde iure iure nam nihil distinctio ipsum.
                  example: Nobis aperiam.
                - name: password
                  in: path
                  description: User password
                  required: true
                  schema:
                    type: string
                    description: User password
                    example: Ipsum voluptatem.
                  example: Et eos recusandae quod porro.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Qui laudantium voluptatem assumenda ratione rem tempora.
                            example: Debitis illo iusto maxime voluptas aliquid totam.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Accusamus temporibus iure autem rerum aperiam commodi.
                            example: Et provident ab ea alias minus.
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 65
                        - 117
                        - 116
                        - 32
                        - 100
                        - 111
                        - 108
                        - 111
                        - 114
                        - 105
                        - 98
                        - 117
                        - 115
                        - 32
                        - 99
                        - 111
                        - 110
                        - 115
                        - 101
                        - 113
                        - 117
                        - 97
                        - 116
                        - 117
                        - 114
                        - 32
                        - 97
                        - 117
                        - 116
                        - 46
                    format: binary
                  example:
                    - 69
                    - 115
                    - 116
                    - 32
                    - 100
                    - 111
                    - 108
                    - 111
                    - 114
                    - 32
                    - 108
                    - 105
                    - 98
                    - 101
                    - 114
                    - 111
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Minus cupiditate adipisci omnis ex porro.
                            example: Quas autem eius suscipit laboriosam laborum voluptas.
                    content:
                        application/json:
                            schema:
                                type: boolean
                                example: true
                            example: true
components: {}
tags:
    - name: auth
    - name: upload
