swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - login_header_Authorization: []
    /posts/create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            parameters:
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
                - name: create_post_request_body
                  in: body
                  description: Post info
                  required: true
                  schema:
                    $ref: '#/definitions/PostingsCreatePostRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PostingsCreatePostResponseBody'
                        required:
                            - title
                            - description
                            - price
                            - imageIDs
                            - postID
                            - medium
                            - uploadDate
                            - sold
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /posts/delete/{postID}:
        delete:
            tags:
                - postings
            summary: delete_post postings
            operationId: postings#delete_post
            parameters:
                - name: postID
                  in: path
                  description: Post to delete
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /posts/edit/{postID}:
        put:
            tags:
                - postings
            summary: edit_post postings
            operationId: postings#edit_post
            parameters:
                - name: title
                  in: query
                  description: Post title
                  required: false
                  type: string
                - name: description
                  in: query
                  description: Post description
                  required: false
                  type: string
                - name: price
                  in: query
                  description: Post price
                  required: false
                  type: string
                - name: content
                  in: query
                  description: Image content
                  required: false
                  type: string
                - name: medium
                  in: query
                  description: Art type
                  required: false
                  type: string
                - name: sold
                  in: query
                  description: is sold
                  required: false
                  type: boolean
                - name: imageID
                  in: query
                  description: Image ID
                  required: false
                  type: string
                - name: postID
                  in: path
                  description: Post ID
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PostingsEditPostResponseBody'
                        required:
                            - title
                            - description
                            - price
                            - imageIDs
                            - postID
                            - medium
                            - uploadDate
                            - sold
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /posts/getimages/{postID}:
        get:
            tags:
                - postings
            summary: get_images_for_post postings
            operationId: postings#get_images_for_post
            parameters:
                - name: postID
                  in: path
                  description: Post to get images for
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Et ea dolores reiciendis accusamus.
            schemes:
                - http
    /posts/getpage/{page}:
        get:
            tags:
                - postings
            summary: get_post_page postings
            operationId: postings#get_post_page
            parameters:
                - name: keyword
                  in: query
                  description: Search bar keyword to search for in title and description
                  required: false
                  type: string
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/PostResponse'
            schemes:
                - http
    /posts/getpagefiltered/{page}:
        get:
            tags:
                - postings
            summary: get_post_page_filtered postings
            operationId: postings#get_post_page_filtered
            parameters:
                - name: keyword
                  in: query
                  description: Search bar keyword to search for in title and description
                  required: false
                  type: string
                - name: startDate
                  in: query
                  description: Filter attribute to see posts after given date
                  required: false
                  type: string
                - name: endDate
                  in: query
                  description: Filter attribute to see posts before given date
                  required: false
                  type: string
                - name: medium
                  in: query
                  description: Filter attribute to see posts with given medium type
                  required: false
                  type: string
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/PostResponse'
            schemes:
                - http
    /posts/myposts/{page}:
        get:
            tags:
                - postings
            summary: get_artist_post_page postings
            operationId: postings#get_artist_post_page
            parameters:
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  type: integer
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/PostResponse'
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
                - name: SignupRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SignupSignupRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - signup_header_Authorization: []
definitions:
    PostResponse:
        title: PostResponse
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Hic ut.
            imageIDs:
                type: array
                items:
                    type: string
                    example: Itaque sed commodi aspernatur aliquam.
                description: Image ID
                example:
                    - Qui ea distinctio.
                    - Ullam voluptatem est dolorum.
                    - Distinctio sit esse dolorem cupiditate at.
                    - Consequatur amet illo.
            medium:
                type: string
                description: Art type
                example: Illo cupiditate quae magnam.
            postID:
                type: string
                description: Post ID
                example: Qui deleniti.
            price:
                type: string
                description: Post price
                example: Sed adipisci ducimus ut.
            sold:
                type: boolean
                description: is sold
                example: true
            title:
                type: string
                description: Post title
                example: Vel accusamus.
            uploadDate:
                type: string
                description: Upload Date
                example: Debitis veritatis consequatur error perspiciatis quas ut.
        description: Describes a post response
        example:
            description: Facilis quisquam quam alias amet officiis qui.
            imageIDs:
                - Enim et consequatur et.
                - Adipisci neque fugiat fuga vero exercitationem fugiat.
                - Expedita eius voluptatem.
                - Necessitatibus modi et assumenda ut et.
            medium: Odio saepe.
            postID: Nostrum quia non repellat.
            price: Vitae commodi eos.
            sold: false
            title: Magni accusamus ea dolorum itaque.
            uploadDate: Tenetur aspernatur hic et.
        required:
            - title
            - description
            - price
            - imageIDs
            - postID
            - medium
            - uploadDate
            - sold
    PostResponseResponseBody:
        title: PostResponseResponseBody
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Nam et vel ipsam.
            imageIDs:
                type: array
                items:
                    type: string
                    example: Eligendi qui omnis.
                description: Image ID
                example:
                    - Voluptate est occaecati harum cum officia quas.
                    - Aspernatur voluptates vel vero.
            medium:
                type: string
                description: Art type
                example: Pariatur culpa odio adipisci maiores qui.
            postID:
                type: string
                description: Post ID
                example: Qui provident nam voluptatem quos in.
            price:
                type: string
                description: Post price
                example: Earum voluptatem repudiandae consequatur.
            sold:
                type: boolean
                description: is sold
                example: false
            title:
                type: string
                description: Post title
                example: Eos incidunt neque.
            uploadDate:
                type: string
                description: Upload Date
                example: Recusandae magni necessitatibus sunt.
        description: Describes a post response
        example:
            description: Vel adipisci.
            imageIDs:
                - Illum eum nihil inventore voluptatibus maxime in.
                - Non quidem eos.
            medium: Facere ratione neque.
            postID: Veniam voluptatem aperiam eum non occaecati architecto.
            price: Sapiente labore quia.
            sold: false
            title: Nesciunt quam dolorem minima est maxime rerum.
            uploadDate: Dicta dolorem iure dolor.
        required:
            - title
            - description
            - price
            - imageIDs
            - postID
            - medium
            - uploadDate
            - sold
    PostingsCreatePostRequestBody:
        title: PostingsCreatePostRequestBody
        type: object
        properties:
            content:
                type: array
                items:
                    type: string
                    example: Sint eos velit assumenda non.
                description: Post content
                example:
                    - Aut cupiditate ut aut dolor.
                    - Qui omnis maiores quod accusamus.
                    - Aut est non ad eum modi.
                    - Et sit quia omnis nemo.
            description:
                type: string
                description: Post description
                example: Voluptatem necessitatibus iste qui sit.
            medium:
                type: string
                description: Art type
                example: Voluptatem tempora velit asperiores qui.
            price:
                type: string
                description: Post price
                example: Odio ipsum distinctio error.
            title:
                type: string
                description: Post title
                example: Similique sunt cum quibusdam sed repellendus.
        description: Describes a post payload
        example:
            content:
                - Rem rerum numquam veniam consequatur repudiandae.
                - Rerum porro.
            description: Minus in ratione dolorum dignissimos.
            medium: Officia aut doloremque dolorem autem.
            price: Distinctio fuga vel earum perspiciatis odit.
            title: Optio tenetur assumenda qui velit voluptatibus.
        required:
            - title
            - description
            - price
            - content
            - medium
    PostingsCreatePostResponseBody:
        title: PostingsCreatePostResponseBody
        $ref: '#/definitions/PostResponseResponseBody'
    PostingsEditPostResponseBody:
        title: PostingsEditPostResponseBody
        $ref: '#/definitions/PostResponseResponseBody'
    SignupSignupRequestBody:
        title: SignupSignupRequestBody
        type: object
        properties:
            email:
                type: string
                description: Email
                example: Eos corporis minima qui sit sed.
            firstName:
                type: string
                description: First name
                example: Natus asperiores porro.
            lastName:
                type: string
                description: Last name
                example: Vel sed et tenetur placeat delectus.
            phone:
                type: string
                description: Phone number
                example: Molestiae non quaerat ipsa.
        description: Describes a user
        example:
            email: Eius ipsa beatae iure.
            firstName: Minus et magnam ea omnis.
            lastName: Enim voluptatem.
            phone: Libero doloremque eos repellendus laudantium aut.
        required:
            - firstName
            - lastName
            - phone
            - email
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Secures endpoint by requiring a valid JWT token retrieved via the login endpoint.
        name: Authorization
        in: header
    login_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during login
    signup_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signup
