swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - login_header_Authorization: []
    /posts/create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            parameters:
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
                - name: create_post_request_body
                  in: body
                  description: Post info
                  required: true
                  schema:
                    $ref: '#/definitions/PostingsCreatePostRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PostingsCreatePostResponseBody'
                        required:
                            - title
                            - description
                            - price
                            - imageIDs
                            - postID
                            - medium
                            - uploadDate
                            - sold
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /posts/delete/{postID}:
        delete:
            tags:
                - postings
            summary: delete_post postings
            operationId: postings#delete_post
            parameters:
                - name: postID
                  in: path
                  description: Post to delete
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /posts/edit/{postID}:
        put:
            tags:
                - postings
            summary: edit_post postings
            operationId: postings#edit_post
            parameters:
                - name: title
                  in: query
                  description: Post title
                  required: false
                  type: string
                - name: description
                  in: query
                  description: Post description
                  required: false
                  type: string
                - name: price
                  in: query
                  description: Post price
                  required: false
                  type: string
                - name: content
                  in: query
                  description: Image content
                  required: false
                  type: string
                - name: medium
                  in: query
                  description: Art type
                  required: false
                  type: string
                - name: sold
                  in: query
                  description: is sold
                  required: false
                  type: boolean
                - name: imageID
                  in: query
                  description: Image ID
                  required: false
                  type: string
                - name: postID
                  in: path
                  description: Post ID
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PostingsEditPostResponseBody'
                        required:
                            - title
                            - description
                            - price
                            - imageIDs
                            - postID
                            - medium
                            - uploadDate
                            - sold
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /posts/getimages/{postID}:
        get:
            tags:
                - postings
            summary: get_images_for_post postings
            operationId: postings#get_images_for_post
            parameters:
                - name: postID
                  in: path
                  description: Post to get images for
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            type: string
                            example: Magni accusamus ea dolorum itaque.
            schemes:
                - http
    /posts/getpage/{page}:
        get:
            tags:
                - postings
            summary: get_post_page postings
            operationId: postings#get_post_page
            parameters:
                - name: keyword
                  in: query
                  description: Search bar keyword to search for in title and description
                  required: false
                  type: string
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/PostResponse'
            schemes:
                - http
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
                - name: SignupRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SignupSignupRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - signup_header_Authorization: []
definitions:
    PostResponse:
        title: PostResponse
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Aut est non ad eum modi.
            imageIDs:
                type: array
                items:
                    type: string
                    example: Voluptatem tempora velit asperiores qui.
                description: Image ID
                example:
                    - Tenetur assumenda qui velit.
                    - Nam minus in.
                    - Dolorum dignissimos.
            medium:
                type: string
                description: Art type
                example: Ex rem rerum numquam veniam.
            postID:
                type: string
                description: Post ID
                example: Distinctio fuga vel earum perspiciatis odit.
            price:
                type: string
                description: Post price
                example: Et sit quia omnis nemo.
            sold:
                type: boolean
                description: is sold
                example: false
            title:
                type: string
                description: Post title
                example: Qui omnis maiores quod accusamus.
            uploadDate:
                type: string
                description: Upload Date
                example: Repudiandae quo rerum porro eius officia.
        description: Describes a post response
        example:
            description: Ut debitis sed adipisci ducimus ut voluptas.
            imageIDs:
                - Voluptatem ullam voluptatem est.
                - Nisi distinctio sit.
                - Dolorem cupiditate at.
                - Consequatur amet illo.
            medium: Illo cupiditate quae magnam.
            postID: Qui deleniti.
            price: Sed commodi aspernatur aliquam quae consequuntur qui.
            sold: true
            title: Dolorem autem provident vel accusamus delectus.
            uploadDate: Debitis veritatis consequatur error perspiciatis quas ut.
        required:
            - title
            - description
            - price
            - imageIDs
            - postID
            - medium
            - uploadDate
            - sold
    PostResponseResponseBody:
        title: PostResponseResponseBody
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Ad voluptatem id dolor autem iusto.
            imageIDs:
                type: array
                items:
                    type: string
                    example: Porro qui vel sed et tenetur.
                description: Image ID
                example:
                    - Animi molestiae non quaerat ipsa.
                    - Eos corporis minima qui sit sed.
            medium:
                type: string
                description: Art type
                example: Enim voluptatem.
            postID:
                type: string
                description: Post ID
                example: Minus et magnam ea omnis.
            price:
                type: string
                description: Post price
                example: Qui unde natus.
            sold:
                type: boolean
                description: is sold
                example: true
            title:
                type: string
                description: Post title
                example: Nemo numquam iste.
            uploadDate:
                type: string
                description: Upload Date
                example: Libero doloremque eos repellendus laudantium aut.
        description: Describes a post response
        example:
            description: Neque et.
            imageIDs:
                - Consequatur voluptatibus eligendi qui.
                - Eum enim voluptate.
                - Occaecati harum.
            medium: Aspernatur voluptates vel vero.
            postID: Officia quas.
            price: Et vel ipsam suscipit earum.
            sold: false
            title: Ipsa beatae iure consequatur eos.
            uploadDate: Qui provident nam voluptatem quos in.
        required:
            - title
            - description
            - price
            - imageIDs
            - postID
            - medium
            - uploadDate
            - sold
    PostingsCreatePostRequestBody:
        title: PostingsCreatePostRequestBody
        type: object
        properties:
            content:
                type: array
                items:
                    type: string
                    example: Iure vel adipisci.
                description: Post content
                example:
                    - Labore quia hic non.
                    - Eum nihil inventore voluptatibus maxime in sunt.
            description:
                type: string
                description: Post description
                example: Magni necessitatibus sunt corrupti sequi nesciunt.
            medium:
                type: string
                description: Art type
                example: Quidem eos maxime veniam voluptatem.
            price:
                type: string
                description: Post price
                example: Dolorem minima est maxime.
            title:
                type: string
                description: Post title
                example: Culpa odio adipisci maiores qui animi.
        description: Describes a post payload
        example:
            content:
                - Necessitatibus iste qui sit.
                - Odio ipsum distinctio error.
                - Sint eos velit assumenda non.
            description: Quidem dicta dolorem iure dolor exercitationem.
            medium: Eaque aut cupiditate ut aut dolor.
            price: Similique sunt cum quibusdam sed repellendus.
            title: Eum non occaecati architecto et facere ratione.
        required:
            - title
            - description
            - price
            - content
            - medium
    PostingsCreatePostResponseBody:
        title: PostingsCreatePostResponseBody
        $ref: '#/definitions/PostResponseResponseBody'
    PostingsEditPostResponseBody:
        title: PostingsEditPostResponseBody
        $ref: '#/definitions/PostResponseResponseBody'
    SignupSignupRequestBody:
        title: SignupSignupRequestBody
        type: object
        properties:
            email:
                type: string
                description: Email
                example: Odit quia culpa vero sed.
            firstName:
                type: string
                description: First name
                example: In vero voluptatem saepe tempore eius ducimus.
            lastName:
                type: string
                description: Last name
                example: Sit distinctio est corrupti suscipit aperiam aut.
            phone:
                type: string
                description: Phone number
                example: Aut sunt ut.
        description: Describes a user
        example:
            email: Id ex qui occaecati consectetur ratione.
            firstName: Cumque mollitia et minus.
            lastName: Veritatis delectus eaque.
            phone: Cum dolor totam sint saepe aperiam non.
        required:
            - firstName
            - lastName
            - phone
            - email
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Secures endpoint by requiring a valid JWT token retrieved via the login endpoint.
        name: Authorization
        in: header
    login_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during login
    signup_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signup
