openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            requestBody:
                description: Post info
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Post'
                        example:
                            content: Aut et atque.
                            description: Quae autem quia nemo iste similique veritatis.
                            medium: Aut animi et deserunt est.
                            price: At ad.
                            title: Ut molestiae nihil ipsam voluptatem explicabo qui.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostingscreatePostResponseBody'
                            example:
                                description: Officiis est optio voluptates qui recusandae sit.
                                imageID: Excepturi ut voluptatum.
                                medium: Quod aut alias optio quidem ducimus.
                                postID: Dignissimos sed eius odio commodi eos consequatur.
                                price: Dolorem eligendi aut consequatur minima rem tempora.
                                sold: false
                                title: Ab enim aut et quas quo.
                                uploadDate: Aut qui cum temporibus asperiores qui.
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Eaque ut.
                            example: Et sit quia omnis nemo.
            security:
                - login_header_Authorization: []
    /posts/delete/{postID}:
        delete:
            tags:
                - postings
            summary: delete_post postings
            operationId: postings#delete_post
            parameters:
                - name: postID
                  in: path
                  description: Post to delete
                  required: true
                  schema:
                    type: string
                    description: Post to delete
                    example: Optio tenetur assumenda qui velit voluptatibus.
                  example: Minus in ratione dolorum dignissimos.
            responses:
                "204":
                    description: No Content response.
    /posts/getimages/{postID}:
        get:
            tags:
                - postings
            summary: get_images_for_post postings
            operationId: postings#get_images_for_post
            parameters:
                - name: postID
                  in: path
                  description: Post to get images for
                  required: true
                  schema:
                    type: string
                    description: Post to get images for
                    example: Earum perspiciatis odit.
                  example: Ex rem rerum numquam veniam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Distinctio error est sint eos.
                                example:
                                    - Non nihil eaque aut cupiditate ut aut.
                                    - Quo qui omnis maiores.
                                    - Accusamus rerum aut.
                                    - Non ad eum modi.
                            example:
                                - Quo rerum porro eius.
                                - Aut doloremque dolorem autem provident vel accusamus.
    /posts/getpage/{page}:
        get:
            tags:
                - postings
            summary: get_post_page postings
            operationId: postings#get_post_page
            parameters:
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  schema:
                    type: integer
                    description: Page to get posts for
                    example: 7054321787732551844
                    format: int64
                  example: 6177084043458317167
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/PostResponse'
                                example:
                                    - description: Reiciendis voluptas in autem dolorem.
                                      imageID: Unde vero.
                                      medium: Unde quod.
                                      postID: Laborum ut iste et harum.
                                      price: Corporis ipsum neque.
                                      sold: false
                                      title: Et incidunt assumenda sequi.
                                      uploadDate: Autem neque numquam.
                                    - description: Reiciendis voluptas in autem dolorem.
                                      imageID: Unde vero.
                                      medium: Unde quod.
                                      postID: Laborum ut iste et harum.
                                      price: Corporis ipsum neque.
                                      sold: false
                                      title: Et incidunt assumenda sequi.
                                      uploadDate: Autem neque numquam.
                                    - description: Reiciendis voluptas in autem dolorem.
                                      imageID: Unde vero.
                                      medium: Unde quod.
                                      postID: Laborum ut iste et harum.
                                      price: Corporis ipsum neque.
                                      sold: false
                                      title: Et incidunt assumenda sequi.
                                      uploadDate: Autem neque numquam.
                            example:
                                - description: Reiciendis voluptas in autem dolorem.
                                  imageID: Unde vero.
                                  medium: Unde quod.
                                  postID: Laborum ut iste et harum.
                                  price: Corporis ipsum neque.
                                  sold: false
                                  title: Et incidunt assumenda sequi.
                                  uploadDate: Autem neque numquam.
                                - description: Reiciendis voluptas in autem dolorem.
                                  imageID: Unde vero.
                                  medium: Unde quod.
                                  postID: Laborum ut iste et harum.
                                  price: Corporis ipsum neque.
                                  sold: false
                                  title: Et incidunt assumenda sequi.
                                  uploadDate: Autem neque numquam.
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
                        example:
                            email: Magnam non voluptas aut vero pariatur.
                            firstName: Quas aut id placeat.
                            lastName: Expedita sunt culpa non voluptatibus cupiditate ea.
                            phone: Ut beatae.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Molestiae non quaerat ipsa.
                            example: Voluptatem tempora velit asperiores qui.
            security:
                - signup_header_Authorization: []
components:
    schemas:
        Post:
            type: object
            properties:
                content:
                    type: string
                    description: Post content
                    example: Libero doloremque eos repellendus laudantium aut.
                description:
                    type: string
                    description: Post description
                    example: Minus et magnam ea omnis.
                medium:
                    type: string
                    description: Art type
                    example: Eius ipsa beatae iure.
                price:
                    type: string
                    description: Post price
                    example: Enim voluptatem.
                title:
                    type: string
                    description: Post title
                    example: Eos corporis minima qui sit sed.
            description: Describes a post
            example:
                content: Eligendi qui omnis.
                description: Nam et vel ipsam.
                medium: Enim voluptate est occaecati.
                price: Earum voluptatem repudiandae consequatur.
                title: Eos incidunt neque.
            required:
                - title
                - description
                - price
                - content
                - medium
        PostResponse:
            type: object
            properties:
                description:
                    type: string
                    description: Post description
                    example: Vero officiis qui.
                imageID:
                    type: string
                    description: Image ID
                    example: Culpa odio adipisci maiores qui animi.
                medium:
                    type: string
                    description: Art type
                    example: Dolorem minima est maxime.
                postID:
                    type: string
                    description: Post ID
                    example: Magni necessitatibus sunt corrupti sequi nesciunt.
                price:
                    type: string
                    description: Post price
                    example: Nam voluptatem quos in velit.
                sold:
                    type: boolean
                    description: is sold
                    example: true
                title:
                    type: string
                    description: Post title
                    example: Cum officia quas deleniti aspernatur voluptates.
                uploadDate:
                    type: string
                    description: Upload Date
                    example: Iure vel adipisci.
            description: Describes a post
            example:
                description: Eum nihil inventore voluptatibus maxime in sunt.
                imageID: Eum non occaecati architecto et facere ratione.
                medium: Similique sunt cum quibusdam sed repellendus.
                postID: Quidem dicta dolorem iure dolor exercitationem.
                price: Quidem eos maxime veniam voluptatem.
                sold: true
                title: Labore quia hic non.
                uploadDate: Voluptatem necessitatibus iste qui sit.
            required:
                - title
                - description
                - price
                - imageID
                - postID
                - medium
                - uploadDate
                - sold
        PostingscreatePostResponseBody:
            $ref: '#/components/schemas/PostResponse'
        User:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Ratione asperiores nemo numquam iste sed ad.
                firstName:
                    type: string
                    description: First name
                    example: Dolor totam.
                lastName:
                    type: string
                    description: Last name
                    example: Saepe aperiam.
                phone:
                    type: string
                    description: Phone number
                    example: Voluptas id ex qui occaecati.
            description: Describes a user
            example:
                email: Vel sed et tenetur placeat delectus.
                firstName: Id dolor autem.
                lastName: Est qui.
                phone: Natus asperiores porro.
            required:
                - firstName
                - lastName
                - phone
                - email
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: postings
