openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quae autem quia nemo iste similique veritatis.
                            example: Aut qui cum temporibus asperiores qui.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SignupRequestBody'
                        example:
                            email: Laborum ut iste et harum.
                            firstName: Corporis ipsum neque.
                            lastName: Unde vero.
                            phone: Unde quod.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Dignissimos sed eius odio commodi eos consequatur.
                            example: Eveniet incidunt et ut consequatur.
            security:
                - signup_header_Authorization: []
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 86
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 115
                        - 32
                        - 113
                        - 117
                        - 111
                        - 46
                    format: binary
                  example:
                    - 81
                    - 117
                    - 97
                    - 115
                    - 105
                    - 32
                    - 110
                    - 111
                    - 110
                    - 32
                    - 113
                    - 117
                    - 105
                    - 32
                    - 101
                    - 115
                    - 115
                    - 101
                    - 32
                    - 110
                    - 111
                    - 110
                    - 32
                    - 112
                    - 114
                    - 97
                    - 101
                    - 115
                    - 101
                    - 110
                    - 116
                    - 105
                    - 117
                    - 109
                    - 32
                    - 101
                    - 120
                    - 112
                    - 101
                    - 100
                    - 105
                    - 116
                    - 97
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Modi dolores laborum.
                            example: Incidunt et ipsum facilis.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quod aut alias optio quidem ducimus.
                            example: Neque praesentium distinctio impedit perferendis aut.
            security:
                - jwt_header_Authorization: []
components:
    schemas:
        SignupRequestBody:
            type: object
            properties:
                email:
                    type: string
                    description: User email
                    example: Aut animi et deserunt est.
                firstName:
                    type: string
                    description: User first name
                    example: At ad.
                lastName:
                    type: string
                    description: User last name
                    example: Aut et atque.
                phone:
                    type: string
                    description: User phone number
                    example: Doloremque ut vel.
            example:
                email: Dolorem eligendi aut consequatur minima rem tempora.
                firstName: Ab enim aut et quas quo.
                lastName: Officiis est optio voluptates qui recusandae sit.
                phone: Excepturi ut voluptatum.
            required:
                - firstName
                - lastName
                - email
                - phone
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: upload
