openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for auth
paths:
    /login:
        post:
            tags:
                - auth
            summary: Login auth
            operationId: auth#Login
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Voluptas soluta.
                            example: Qui voluptatibus.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Quia laborum quam voluptatem quia sapiente est.
                            example: Natus dignissimos perferendis autem et et qui.
            security:
                - basic_header_Authorization: []
    /signup/{username}/{password}:
        get:
            tags:
                - auth
            summary: Signup auth
            operationId: auth#Signup
            parameters:
                - name: username
                  in: path
                  description: Raw username
                  required: true
                  schema:
                    type: string
                    description: Raw username
                    example: Non voluptatem impedit rem.
                  example: Consectetur voluptas rem error doloremque sunt.
                - name: password
                  in: path
                  description: User password
                  required: true
                  schema:
                    type: string
                    description: User password
                    example: Repudiandae quod consectetur quia rerum.
                  example: Et minus illum ducimus et.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Unde iure iure nam nihil distinctio ipsum.
                            example: Ipsum voluptatem.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Accusamus temporibus iure autem rerum aperiam commodi.
                            example: Et eos recusandae quod porro.
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 81
                        - 117
                        - 105
                        - 32
                        - 108
                        - 97
                        - 117
                        - 100
                        - 97
                        - 110
                        - 116
                        - 105
                        - 117
                        - 109
                        - 32
                        - 118
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 116
                        - 101
                        - 109
                        - 32
                        - 97
                        - 115
                        - 115
                        - 117
                        - 109
                        - 101
                        - 110
                        - 100
                        - 97
                        - 32
                        - 114
                        - 97
                        - 116
                        - 105
                        - 111
                        - 110
                        - 101
                        - 32
                        - 114
                        - 101
                        - 109
                        - 32
                        - 116
                        - 101
                        - 109
                        - 112
                        - 111
                        - 114
                        - 97
                        - 46
                    format: binary
                  example:
                    - 86
                    - 101
                    - 108
                    - 32
                    - 98
                    - 108
                    - 97
                    - 110
                    - 100
                    - 105
                    - 116
                    - 105
                    - 105
                    - 115
                    - 32
                    - 114
                    - 97
                    - 116
                    - 105
                    - 111
                    - 110
                    - 101
                    - 32
                    - 99
                    - 111
                    - 114
                    - 114
                    - 117
                    - 112
                    - 116
                    - 105
                    - 32
                    - 110
                    - 111
                    - 115
                    - 116
                    - 114
                    - 117
                    - 109
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Debitis illo iusto maxime voluptas aliquid totam.
                            example: Aut doloribus consequatur aut.
                    content:
                        application/json:
                            schema:
                                type: boolean
                                example: true
                            example: false
components:
    securitySchemes:
        basic_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: auth
    - name: upload
