swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            parameters:
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
                - name: create_post_request_body
                  in: body
                  description: Post info
                  required: true
                  schema:
                    $ref: '#/definitions/PostingsCreatePostRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/PostingsCreatePostResponseBody'
                        required:
                            - title
                            - description
                            - price
                            - imageID
                            - postID
                            - uploadDate
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
                - name: SignupRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SignupSignupRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - signup_header_Authorization: []
definitions:
    PostResponseResponseBody:
        title: PostResponseResponseBody
        type: object
        properties:
            description:
                type: string
                description: Post description
                example: Voluptas quo.
            imageID:
                type: string
                description: Image ID
                example: Modi dolores laborum.
            postID:
                type: string
                description: Post ID
                example: Repudiandae tempore molestiae illo.
            price:
                type: string
                description: Post price
                example: Quasi non qui esse non praesentium expedita.
            title:
                type: string
                description: Post title
                example: Eveniet incidunt et ut consequatur.
            uploadDate:
                type: string
                description: Upload Date
                example: Incidunt et ipsum facilis.
        description: Describes a post
        example:
            description: Voluptas ipsum rerum iure minima nihil odio.
            imageID: Eaque nesciunt impedit aut rerum qui.
            postID: Minima quis numquam.
            price: Dolorem aut hic dolores est.
            title: Neque praesentium distinctio impedit perferendis aut.
            uploadDate: Excepturi quos ut.
        required:
            - title
            - description
            - price
            - imageID
            - postID
            - uploadDate
    PostingsCreatePostRequestBody:
        title: PostingsCreatePostRequestBody
        type: object
        properties:
            content:
                type: string
                description: Post content
                example:
                    - 69
                    - 115
                    - 116
                    - 32
                    - 105
                    - 110
                    - 118
                    - 101
                    - 110
                    - 116
                    - 111
                    - 114
                    - 101
                    - 46
                format: byte
            description:
                type: string
                description: Post description
                example: Tempora vero.
            price:
                type: string
                description: Post price
                example: Provident ipsa dignissimos sed.
            title:
                type: string
                description: Post title
                example: Sit et quaerat non nobis repudiandae autem.
        description: Describes a post
        example:
            content:
                - 68
                - 105
                - 115
                - 116
                - 105
                - 110
                - 99
                - 116
                - 105
                - 111
                - 32
                - 117
                - 116
                - 32
                - 108
                - 97
                - 98
                - 111
                - 114
                - 105
                - 111
                - 115
                - 97
                - 109
                - 32
                - 110
                - 97
                - 109
                - 32
                - 104
                - 105
                - 99
                - 32
                - 118
                - 101
                - 108
                - 32
                - 118
                - 101
                - 108
                - 46
            description: Atque voluptates at perferendis.
            price: Provident dignissimos.
            title: Cupiditate voluptatem a eaque odit.
        required:
            - title
            - description
            - price
            - content
    PostingsCreatePostResponseBody:
        title: PostingsCreatePostResponseBody
        $ref: '#/definitions/PostResponseResponseBody'
    SignupSignupRequestBody:
        title: SignupSignupRequestBody
        type: object
        properties:
            email:
                type: string
                description: Email
                example: Dolorem eligendi aut consequatur minima rem tempora.
            firstName:
                type: string
                description: First name
                example: Doloremque ut vel.
            lastName:
                type: string
                description: Last name
                example: Ab enim aut et quas quo.
            phone:
                type: string
                description: Phone number
                example: Officiis est optio voluptates qui recusandae sit.
        description: Describes a user
        example:
            email: Aut qui cum temporibus asperiores qui.
            firstName: Excepturi ut voluptatum.
            lastName: Dignissimos sed eius odio commodi eos consequatur.
            phone: Quod aut alias optio quidem ducimus.
        required:
            - firstName
            - lastName
            - phone
            - email
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
        name: Authorization
        in: header
    login_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
    signup_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
