swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            parameters:
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            parameters:
                - name: firstName
                  in: query
                  description: User first name
                  required: true
                  type: string
                - name: lastName
                  in: query
                  description: User last name
                  required: true
                  type: string
                - name: email
                  in: query
                  description: User email
                  required: true
                  type: string
                - name: phone
                  in: query
                  description: User phone number
                  required: true
                  type: string
                - name: Authorization
                  in: header
                  description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
            schemes:
                - http
            security:
                - signup_header_Authorization: []
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  type: string
                  format: byte
                - name: Authorization
                  in: header
                  description: jwt used for auth
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: string
                    headers:
                        Access-Control-Allow-Origin:
                            type: string
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
        name: Authorization
        in: header
    login_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
    signup_header_Authorization:
        type: basic
        description: Basic authentication used to authenticate security principal during signin
