openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            requestBody:
                description: Post info
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Post'
                        example:
                            content:
                                - 65
                                - 117
                                - 116
                                - 101
                                - 109
                                - 32
                                - 113
                                - 117
                                - 105
                                - 97
                                - 32
                                - 118
                                - 101
                                - 114
                                - 105
                                - 116
                                - 97
                                - 116
                                - 105
                                - 115
                                - 32
                                - 100
                                - 111
                                - 108
                                - 111
                                - 114
                                - 101
                                - 109
                                - 46
                            description: Magnam non voluptas aut vero pariatur.
                            price: Ut in sapiente illo explicabo aut.
                            title: Voluptatibus cupiditate ea cum ut beatae.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                description: Upload Date
                                example: Odit deleniti non praesentium molestiae consequuntur.
                            example: Voluptas commodi.
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Repudiandae tempore molestiae illo.
                            example: Eum molestiae ut deleniti laborum.
            security:
                - login_header_Authorization: []
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
                        example:
                            email:
                                - 67
                                - 111
                                - 109
                                - 109
                                - 111
                                - 100
                                - 105
                                - 32
                                - 111
                                - 102
                                - 102
                                - 105
                                - 99
                                - 105
                                - 105
                                - 115
                                - 32
                                - 110
                                - 117
                                - 109
                                - 113
                                - 117
                                - 97
                                - 109
                                - 32
                                - 109
                                - 111
                                - 108
                                - 101
                                - 115
                                - 116
                                - 105
                                - 97
                                - 101
                                - 46
                            firstName: Velit rerum occaecati quia.
                            lastName: Voluptate quod.
                            phone: Dolorum aut aut impedit nisi odio.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Tempora vero.
                            example: Minus quia labore recusandae quae omnis et.
            security:
                - signup_header_Authorization: []
components:
    schemas:
        Post:
            type: object
            properties:
                content:
                    type: string
                    description: Post content
                    example:
                        - 65
                        - 116
                        - 113
                        - 117
                        - 101
                        - 32
                        - 118
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 116
                        - 101
                        - 115
                        - 32
                        - 97
                        - 116
                        - 32
                        - 112
                        - 101
                        - 114
                        - 102
                        - 101
                        - 114
                        - 101
                        - 110
                        - 100
                        - 105
                        - 115
                        - 46
                    format: binary
                description:
                    type: string
                    description: Post description
                    example: Est inventore.
                price:
                    type: string
                    description: Post price
                    example: Cupiditate voluptatem a eaque odit.
                title:
                    type: string
                    description: Post title
                    example: Provident ipsa dignissimos sed.
            description: Describes a post
            example:
                content:
                    - 65
                    - 114
                    - 99
                    - 104
                    - 105
                    - 116
                    - 101
                    - 99
                    - 116
                    - 111
                    - 32
                    - 101
                    - 116
                    - 32
                    - 101
                    - 120
                    - 112
                    - 101
                    - 100
                    - 105
                    - 116
                    - 97
                    - 32
                    - 101
                    - 117
                    - 109
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 105
                    - 98
                    - 117
                    - 115
                    - 32
                    - 116
                    - 101
                    - 110
                    - 101
                    - 116
                    - 117
                    - 114
                    - 32
                    - 110
                    - 111
                    - 110
                    - 46
                description: Distinctio ut laboriosam nam hic vel vel.
                price: Dignissimos repellendus quia.
                title: Provident dignissimos.
            required:
                - title
                - description
                - price
                - content
        User:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example:
                        - 68
                        - 111
                        - 108
                        - 111
                        - 114
                        - 101
                        - 109
                        - 32
                        - 97
                        - 117
                        - 116
                        - 32
                        - 104
                        - 105
                        - 99
                        - 32
                        - 100
                        - 111
                        - 108
                        - 111
                        - 114
                        - 101
                        - 115
                        - 32
                        - 101
                        - 115
                        - 116
                        - 46
                    format: binary
                firstName:
                    type: string
                    description: First name
                    example: Incidunt et ipsum facilis.
                lastName:
                    type: string
                    description: Last name
                    example: Neque praesentium distinctio impedit perferendis aut.
                phone:
                    type: string
                    description: Phone number
                    example: Voluptas ipsum rerum iure minima nihil odio.
            description: Describes a user
            example:
                email:
                    - 83
                    - 105
                    - 116
                    - 32
                    - 101
                    - 116
                    - 32
                    - 113
                    - 117
                    - 97
                    - 101
                    - 114
                    - 97
                    - 116
                    - 32
                    - 110
                    - 111
                    - 110
                    - 32
                    - 110
                    - 111
                    - 98
                    - 105
                    - 115
                    - 32
                    - 114
                    - 101
                    - 112
                    - 117
                    - 100
                    - 105
                    - 97
                    - 110
                    - 100
                    - 97
                    - 101
                    - 32
                    - 97
                    - 117
                    - 116
                    - 101
                    - 109
                    - 46
                firstName: Eaque nesciunt impedit aut rerum qui.
                lastName: Minima quis numquam.
                phone: Excepturi quos ut.
            required:
                - firstName
                - lastName
                - phone
                - email
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: postings
