openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /create:
        post:
            tags:
                - postings
            summary: create_post postings
            operationId: postings#create_post
            requestBody:
                description: Post info
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Post'
                        example:
                            content: Aut et atque.
                            description: Quae autem quia nemo iste similique veritatis.
                            price: At ad.
                            title: Ut molestiae nihil ipsam voluptatem explicabo qui.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostingscreatePostResponseBody'
                            example:
                                description: Ab enim aut et quas quo.
                                imageID: Dolorem eligendi aut consequatur minima rem tempora.
                                postID: Excepturi ut voluptatum.
                                price: Officiis est optio voluptates qui recusandae sit.
                                title: Doloremque ut vel.
                                uploadDate: Dignissimos sed eius odio commodi eos consequatur.
            security:
                - jwt_header_Authorization: []
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Id ut et.
                            example: Sapiente labore quia.
            security:
                - login_header_Authorization: []
    /posts/getimages/{postID}:
        get:
            tags:
                - postings
            summary: get_images_for_post postings
            operationId: postings#get_images_for_post
            parameters:
                - name: postID
                  in: path
                  description: Post to get images for
                  required: true
                  schema:
                    type: string
                    description: Post to get images for
                    example: Eos maxime veniam voluptatem aperiam eum non.
                  example: Architecto et facere ratione neque.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                                    example: Odio adipisci.
                                example:
                                    - Animi recusandae magni necessitatibus.
                                    - Corrupti sequi nesciunt.
                                    - Dolorem minima est maxime.
                                    - Iure vel adipisci.
                            example:
                                - Dolorem iure dolor exercitationem nisi.
                                - Sunt cum quibusdam sed repellendus.
                                - Voluptatem necessitatibus iste qui sit.
    /posts/getpage/{page}:
        get:
            tags:
                - postings
            summary: get_post_page postings
            operationId: postings#get_post_page
            parameters:
                - name: page
                  in: path
                  description: Page to get posts for
                  required: true
                  schema:
                    type: integer
                    description: Page to get posts for
                    example: 5285461511493172875
                    format: int64
                  example: 119223619063405366
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/PostResponse'
                                example:
                                    - description: Et incidunt assumenda sequi.
                                      imageID: Corporis ipsum neque.
                                      postID: Unde vero.
                                      price: Reiciendis voluptas in autem dolorem.
                                      title: Accusantium ipsam nisi pariatur magnam.
                                      uploadDate: Laborum ut iste et harum.
                                    - description: Et incidunt assumenda sequi.
                                      imageID: Corporis ipsum neque.
                                      postID: Unde vero.
                                      price: Reiciendis voluptas in autem dolorem.
                                      title: Accusantium ipsam nisi pariatur magnam.
                                      uploadDate: Laborum ut iste et harum.
                                    - description: Et incidunt assumenda sequi.
                                      imageID: Corporis ipsum neque.
                                      postID: Unde vero.
                                      price: Reiciendis voluptas in autem dolorem.
                                      title: Accusantium ipsam nisi pariatur magnam.
                                      uploadDate: Laborum ut iste et harum.
                                    - description: Et incidunt assumenda sequi.
                                      imageID: Corporis ipsum neque.
                                      postID: Unde vero.
                                      price: Reiciendis voluptas in autem dolorem.
                                      title: Accusantium ipsam nisi pariatur magnam.
                                      uploadDate: Laborum ut iste et harum.
                            example:
                                - description: Et incidunt assumenda sequi.
                                  imageID: Corporis ipsum neque.
                                  postID: Unde vero.
                                  price: Reiciendis voluptas in autem dolorem.
                                  title: Accusantium ipsam nisi pariatur magnam.
                                  uploadDate: Laborum ut iste et harum.
                                - description: Et incidunt assumenda sequi.
                                  imageID: Corporis ipsum neque.
                                  postID: Unde vero.
                                  price: Reiciendis voluptas in autem dolorem.
                                  title: Accusantium ipsam nisi pariatur magnam.
                                  uploadDate: Laborum ut iste et harum.
    /signup:
        post:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
                        example:
                            email: Magnam non voluptas aut vero pariatur.
                            firstName: Earum quia aut.
                            lastName: Aut id placeat voluptate expedita sunt culpa.
                            phone: Voluptatibus cupiditate ea cum ut beatae.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Cum dolor totam sint saepe aperiam non.
                            example: Non illum eum nihil inventore voluptatibus maxime.
            security:
                - signup_header_Authorization: []
components:
    schemas:
        Post:
            type: object
            properties:
                content:
                    type: string
                    description: Post content
                    example: Qui unde natus.
                description:
                    type: string
                    description: Post description
                    example: Nemo numquam iste.
                price:
                    type: string
                    description: Post price
                    example: Ad voluptatem id dolor autem iusto.
                title:
                    type: string
                    description: Post title
                    example: Id ex qui occaecati consectetur ratione.
            description: Describes a post
            example:
                content: Qui sit.
                description: Delectus animi.
                price: Non quaerat ipsa enim eos corporis.
                title: Porro qui vel sed et tenetur.
            required:
                - title
                - description
                - price
                - content
        PostResponse:
            type: object
            properties:
                description:
                    type: string
                    description: Post description
                    example: Omnis quo enim voluptatem eligendi libero doloremque.
                imageID:
                    type: string
                    description: Image ID
                    example: Eius ipsa beatae iure.
                postID:
                    type: string
                    description: Post ID
                    example: Eos incidunt neque.
                price:
                    type: string
                    description: Post price
                    example: Repellendus laudantium aut.
                title:
                    type: string
                    description: Post title
                    example: Voluptas minus et magnam.
                uploadDate:
                    type: string
                    description: Upload Date
                    example: Nam et vel ipsam.
            description: Describes a post
            example:
                description: Eligendi qui omnis.
                imageID: Cum officia quas deleniti aspernatur voluptates.
                postID: Vero officiis qui.
                price: Enim voluptate est occaecati.
                title: Earum voluptatem repudiandae consequatur.
                uploadDate: Nam voluptatem quos in velit.
            required:
                - title
                - description
                - price
                - imageID
                - postID
                - uploadDate
        PostingscreatePostResponseBody:
            $ref: '#/components/schemas/PostResponse'
        User:
            type: object
            properties:
                email:
                    type: string
                    description: Email
                    example: Sit distinctio est corrupti suscipit aperiam aut.
                firstName:
                    type: string
                    description: First name
                    example: Vel culpa ut expedita consequatur facilis non.
                lastName:
                    type: string
                    description: Last name
                    example: Dolores praesentium vel blanditiis nihil blanditiis porro.
                phone:
                    type: string
                    description: Phone number
                    example: In vero voluptatem saepe tempore eius ducimus.
            description: Describes a user
            example:
                email: Veritatis delectus eaque.
                firstName: Aut sunt ut.
                lastName: Odit quia culpa vero sed.
                phone: Cumque mollitia et minus.
            required:
                - firstName
                - lastName
                - phone
                - email
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: postings
