openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for login
paths:
    /login:
        post:
            tags:
                - login
            summary: Login login
            operationId: login#Login
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Earum quia aut.
                            example: Voluptatibus cupiditate ea cum ut beatae.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Commodi officiis numquam molestiae.
                            example: Magnam non voluptas aut vero pariatur.
            security:
                - login_header_Authorization: []
    /signup:
        get:
            tags:
                - signup
            summary: Signup signup
            operationId: signup#Signup
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: Ut in sapiente illo explicabo aut.
                            example: Minima nisi.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Nam doloribus dolor commodi consequuntur perferendis ea.
                            example: Ut ut omnis.
            security:
                - signup_header_Authorization: []
    /upload/{content}:
        get:
            tags:
                - upload
            summary: upload_photo upload
            operationId: upload#upload_photo
            parameters:
                - name: content
                  in: path
                  description: photo content
                  required: true
                  schema:
                    type: string
                    description: photo content
                    example:
                        - 85
                        - 116
                        - 32
                        - 109
                        - 111
                        - 108
                        - 101
                        - 115
                        - 116
                        - 105
                        - 97
                        - 101
                        - 32
                        - 110
                        - 105
                        - 104
                        - 105
                        - 108
                        - 32
                        - 105
                        - 112
                        - 115
                        - 97
                        - 109
                        - 32
                        - 118
                        - 111
                        - 108
                        - 117
                        - 112
                        - 116
                        - 97
                        - 116
                        - 101
                        - 109
                        - 32
                        - 101
                        - 120
                        - 112
                        - 108
                        - 105
                        - 99
                        - 97
                        - 98
                        - 111
                        - 32
                        - 113
                        - 117
                        - 105
                        - 46
                    format: binary
                  example:
                    - 81
                    - 117
                    - 97
                    - 101
                    - 32
                    - 97
                    - 117
                    - 116
                    - 101
                    - 109
                    - 32
                    - 113
                    - 117
                    - 105
                    - 97
                    - 32
                    - 110
                    - 101
                    - 109
                    - 111
                    - 32
                    - 105
                    - 115
                    - 116
                    - 101
                    - 32
                    - 115
                    - 105
                    - 109
                    - 105
                    - 108
                    - 105
                    - 113
                    - 117
                    - 101
                    - 32
                    - 118
                    - 101
                    - 114
                    - 105
                    - 116
                    - 97
                    - 116
                    - 105
                    - 115
                    - 46
            responses:
                "200":
                    description: OK response.
                    headers:
                        Access-Control-Allow-Origin:
                            schema:
                                type: string
                                example: At ad.
                            example: Aut animi et deserunt est.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Qui unde et mollitia modi.
                            example: Doloremque ut vel.
            security:
                - jwt_header_Authorization: []
components:
    securitySchemes:
        jwt_header_Authorization:
            type: http
            description: Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint.
            scheme: bearer
        login_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
        signup_header_Authorization:
            type: http
            description: Basic authentication used to authenticate security principal during signin
            scheme: basic
tags:
    - name: login
    - name: signup
    - name: upload
