#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}

echo "Generating Goa code..."

for svc in calc ; do
  goa gen github.com/Locally-Imagined/goa/services/${svc}/design -o services/${svc}
done

cp services/front/gen/http/openapi3.json docs/openapi.json

popd
